// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace account {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class BaseReq;
class PingRequest;
class PongResponse;

// ===================================================================

class BaseReq : public ::google::protobuf::Message {
 public:
  BaseReq();
  virtual ~BaseReq();

  BaseReq(const BaseReq& from);

  inline BaseReq& operator=(const BaseReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseReq& default_instance();

  void Swap(BaseReq* other);

  // implements Message ----------------------------------------------

  BaseReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseReq& from);
  void MergeFrom(const BaseReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 accId = 2;
  inline bool has_accid() const;
  inline void clear_accid();
  static const int kAccIdFieldNumber = 2;
  inline ::google::protobuf::uint32 accid() const;
  inline void set_accid(::google::protobuf::uint32 value);

  // required uint32 sesKey = 1;
  inline bool has_seskey() const;
  inline void clear_seskey();
  static const int kSesKeyFieldNumber = 1;
  inline ::google::protobuf::uint32 seskey() const;
  inline void set_seskey(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:account.BaseReq)
 private:
  inline void set_has_accid();
  inline void clear_has_accid();
  inline void set_has_seskey();
  inline void clear_has_seskey();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 accid_;
  ::google::protobuf::uint32 seskey_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static BaseReq* default_instance_;
};
// -------------------------------------------------------------------

class PingRequest : public ::google::protobuf::Message {
 public:
  PingRequest();
  virtual ~PingRequest();

  PingRequest(const PingRequest& from);

  inline PingRequest& operator=(const PingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingRequest& default_instance();

  void Swap(PingRequest* other);

  // implements Message ----------------------------------------------

  PingRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingRequest& from);
  void MergeFrom(const PingRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .account.BaseReq baseReq = 1;
  inline bool has_basereq() const;
  inline void clear_basereq();
  static const int kBaseReqFieldNumber = 1;
  inline const ::account::BaseReq& basereq() const;
  inline ::account::BaseReq* mutable_basereq();
  inline ::account::BaseReq* release_basereq();
  inline void set_allocated_basereq(::account::BaseReq* basereq);

  // @@protoc_insertion_point(class_scope:account.PingRequest)
 private:
  inline void set_has_basereq();
  inline void clear_has_basereq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::account::BaseReq* basereq_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static PingRequest* default_instance_;
};
// -------------------------------------------------------------------

class PongResponse : public ::google::protobuf::Message {
 public:
  PongResponse();
  virtual ~PongResponse();

  PongResponse(const PongResponse& from);

  inline PongResponse& operator=(const PongResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PongResponse& default_instance();

  void Swap(PongResponse* other);

  // implements Message ----------------------------------------------

  PongResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PongResponse& from);
  void MergeFrom(const PongResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:account.PongResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static PongResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// BaseReq

// required uint32 accId = 2;
inline bool BaseReq::has_accid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseReq::set_has_accid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseReq::clear_has_accid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseReq::clear_accid() {
  accid_ = 0u;
  clear_has_accid();
}
inline ::google::protobuf::uint32 BaseReq::accid() const {
  // @@protoc_insertion_point(field_get:account.BaseReq.accId)
  return accid_;
}
inline void BaseReq::set_accid(::google::protobuf::uint32 value) {
  set_has_accid();
  accid_ = value;
  // @@protoc_insertion_point(field_set:account.BaseReq.accId)
}

// required uint32 sesKey = 1;
inline bool BaseReq::has_seskey() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BaseReq::set_has_seskey() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BaseReq::clear_has_seskey() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BaseReq::clear_seskey() {
  seskey_ = 0u;
  clear_has_seskey();
}
inline ::google::protobuf::uint32 BaseReq::seskey() const {
  // @@protoc_insertion_point(field_get:account.BaseReq.sesKey)
  return seskey_;
}
inline void BaseReq::set_seskey(::google::protobuf::uint32 value) {
  set_has_seskey();
  seskey_ = value;
  // @@protoc_insertion_point(field_set:account.BaseReq.sesKey)
}

// -------------------------------------------------------------------

// PingRequest

// required .account.BaseReq baseReq = 1;
inline bool PingRequest::has_basereq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PingRequest::set_has_basereq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PingRequest::clear_has_basereq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PingRequest::clear_basereq() {
  if (basereq_ != NULL) basereq_->::account::BaseReq::Clear();
  clear_has_basereq();
}
inline const ::account::BaseReq& PingRequest::basereq() const {
  // @@protoc_insertion_point(field_get:account.PingRequest.baseReq)
  return basereq_ != NULL ? *basereq_ : *default_instance_->basereq_;
}
inline ::account::BaseReq* PingRequest::mutable_basereq() {
  set_has_basereq();
  if (basereq_ == NULL) basereq_ = new ::account::BaseReq;
  // @@protoc_insertion_point(field_mutable:account.PingRequest.baseReq)
  return basereq_;
}
inline ::account::BaseReq* PingRequest::release_basereq() {
  clear_has_basereq();
  ::account::BaseReq* temp = basereq_;
  basereq_ = NULL;
  return temp;
}
inline void PingRequest::set_allocated_basereq(::account::BaseReq* basereq) {
  delete basereq_;
  basereq_ = basereq;
  if (basereq) {
    set_has_basereq();
  } else {
    clear_has_basereq();
  }
  // @@protoc_insertion_point(field_set_allocated:account.PingRequest.baseReq)
}

// -------------------------------------------------------------------

// PongResponse


// @@protoc_insertion_point(namespace_scope)

}  // namespace account

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
